#### B2. Build a Discrete Hidden Markov Model (HMM) to analyze DNA sequences and predict gene regions. Use Maximum Likelihood Estimation to train the model with a given dataset of labeled sequences

In [7]:
import numpy as np
from hmmlearn import hmm
from collections import Counter
from hmmlearn.hmm import CategoricalHMM

In [8]:
nucleotide_mapping = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
state_mapping = {'N': 0, 'G': 1}

In [9]:
inv_state_mapping = {0: 'N', 1: 'G'}

In [10]:
train_sequences = ['ATGCG', 'TTCGA', 'GGGTT']
train_states = ['GGGGG', 'NNNGG', 'GGGNN']

In [11]:
observed_sequences = [np.array([nucleotide_mapping[nuc] for nuc in seq]).reshape(-1, 1)
                      for seq in train_sequences]
state_sequences = [np.array([state_mapping[state] for state in states])
                   for states in train_states]

In [12]:
X = np.concatenate(observed_sequences)
lengths = [len(seq) for seq in observed_sequences]

In [13]:
n_states = 2  # Gene, Non-Gene
n_observations = len(nucleotide_mapping)

In [14]:
model = hmm.CategoricalHMM(n_components=n_states, n_iter=100, tol=1e-4, verbose=True)
model.n_features = n_observations

In [15]:
model.fit(X, lengths)

         1     -21.70259808             +nan
         2     -18.18566642      +3.51693166
         3     -17.93139730      +0.25426913
         4     -17.80891104      +0.12248626
         5     -17.75276176      +0.05614927
         6     -17.72138556      +0.03137620
         7     -17.69972976      +0.02165580
         8     -17.68327688      +0.01645289
         9     -17.67044770      +0.01282918
        10     -17.66044380      +0.01000390
        11     -17.65270889      +0.00773491
        12     -17.64679216      +0.00591672
        13     -17.64231349      +0.00447867
        14     -17.63895455      +0.00335894
        15     -17.63645462      +0.00249993
        16     -17.63460532      +0.00184930
        17     -17.63324373      +0.00136159
        18     -17.63224475      +0.00099898
        19     -17.63151370      +0.00073105
        20     -17.63097969      +0.00053401
        21     -17.63059010      +0.00038959
        22     -17.63030609      +0.00028401
        23

CategoricalHMM(n_components=2, n_features=4, n_iter=100,
               random_state=RandomState(MT19937) at 0x1FCD68E7540, tol=0.0001,
               verbose=True)

In [16]:
print("Initial Probabilities (π):")
print(model.startprob_)
print("\nTransition Probabilities (A):")
print(model.transmat_)
print("\nEmission Probabilities (B):")
print(model.emissionprob_)

Initial Probabilities (π):
[9.99964642e-01 3.53577350e-05]

Transition Probabilities (A):
[[9.46126584e-05 9.99905387e-01]
 [6.65291701e-01 3.34708299e-01]]

Emission Probabilities (B):
[[2.80317689e-01 2.80317688e-01 2.02814986e-01 2.36549636e-01]
 [3.62501222e-18 3.30723748e-10 5.78871656e-01 4.21128343e-01]]


In [17]:
test_sequence = "ATGGC"
test_observed = np.array([nucleotide_mapping[nuc] for nuc in test_sequence]).reshape(-1, 1)

In [19]:
predicted_states = model.predict(test_observed)
predicted_labels = [inv_state_mapping[state] for state in predicted_states]

In [20]:
print("\nTest DNA sequence:       ", test_sequence)
print("Predicted gene regions:  ", "".join(predicted_labels))


Test DNA sequence:        ATGGC
Predicted gene regions:   NGNGN
